
spring:
  main:
    banner-mode: off

  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties.hibernate.format_sql: true
    hibernate:
      ddl-auto: update
