
spring:
  main:
    banner-mode: off

  datasource:
    url: ${DATABASE_URL:jdbc:oracle:thin:@//aopdbd05.zit.commerzbank.com:1521/AOPDV02}
    username: 
    password:
    #driver-class-name: 

  jpa:
    show-sql: true
    properties.hibernate.format_sql: true
    hibernate:
      ddl-auto: drop-create





  