apiVersion: v1
kind: Service
metadata:
  name: "${SERVICE_NAME}"
  namespace: "${SERVICE_NAME}"
  labels:
    app: "${SERVICE_NAME}"
    version: "${COMMIT_SHA}"
spec:
  selector:
    app: "${SERVICE_NAME}"
  type: ClusterIP
  ports:
    - name: http-app
      port: 80
      targetPort: 8080
